### ISSUE TITLE
Function definitions need to pattern match on tuples.

### ISSUE THREAD

**Issue by dampfhub** [The-Code-In-Sheep-s-Clothing/BottomUp#1]

**Comment by jsfreischuetz** [comment]
I think that this works from the change yesterday but it is broken in the parser

This is what the parser is giving:
Valdef (Signature "isValid" (Ftype' (Ftype (Ttype' (Ttype [Xtype [Btype "Board"],Xtype [Btype "Position"]])) (Xtype' (Xtype [Btype "Bool"])))))
